show collections
db.restaurants.find({},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({},{_id:0,restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({},{_id:0,restaurant_id:1, name:1, borough:1, "address.zipcode":1})
db.restaurants.find({borough:"Bronx"},{_id:0,restaurant_id:1,name:1})
db.restaurants.find({borough:"Bronx"},{_id:0,restaurant_id:1,name:1}).limit(5)
db.restaurants.find({borough:"Bronx"},{_id:0,restaurant_id:1,name:1}).skip(5).limit(5)
db.restaurants.find({'grades.score':{$gt:90}})
db.restaurants.find({$and:[ {'grades.score': { $gt: 90 }},{'grades.score':{$lt:100}}]} )
db.restaurants.find({'address.coord': { $lt: -95.754168 }} )
db.restaurants.find({$and:[ {'grades.score': { $gt: 70 }},{'address.coord': { $lt: -65.754168 }},{'cuisine': { $ne: 'American ' }} ]} )
db.restaurants.find({'grades.score': { $gt: 70 },'address.coord': { $lt: -65.754168 },'cuisine': { $ne: 'American ' }})
db.restaurants.find({$and:[ {'grades.grade': { $eq: 'A' }},{'borough': { $ne: 'Brooklyn' }},{'cuisine': { $ne: 'American ' }} ]} )
db.restaurants.find({name:/^Wil/i},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({name:/ces$/i},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({name:/Reg/i},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({$and:[{'borough':{$eq:'Bronx'}},{'cuisine': { $in: ['American ','Chinese']}}]})
db.restaurants.find({borough:{$in:['Staten Island','Queens','Bronx','Brooklyn']}},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({borough:{$nin:['Staten Island','Queens','Bronx','Brooklyn']}},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({'grades.score': {$lte:10}},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({$or:[{name:/^Will/i},{$and:[{'cuisine': { $nin: ['American ','Chinese']}},{'cuisine':/fish/i}]}]},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({$and:[{'grades.grade':{$eq:'A'}},{'grades.date':ISODate('2014-08-11T00:00:00Z')},{'grades.score': { $eq: 11 }}]},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({$and:[{'grades.1.grade':{$eq:'A'}},{'grades.1.date':ISODate('2014-08-11T00:00:00Z')},{'grades.1.score': { $eq: 9 }}]},{restaurant_id:1, name:1, borough:1, cuisine:1})
db.restaurants.find({$and:[{'address.coord.1':{$gt:42}},{'address.coord.1':{$lt:52}}]},{_id:0,restaurant_id:1, name:1, address:1, grades:1})
db.restaurants.find({},{_id:0,restaurant_id:1, name:1, address:1, grades:1}).sort({name:1})
db.restaurants.find({},{_id:0,restaurant_id:1, name:1, address:1, grades:1}).sort({name:-1})
db.restaurants.find({},{_id:0,cuisine:1, borough:1}).sort({cuisine:1,borough:-1})
db.restaurants.find({'address.street':{$exists:false}})
db.restaurants.find({'address.coord': {$type: "double"}})
db.restaurants.find({'grades.score':{$mod:[7,0]}},{_id:0,restaurant_id:1, name:1, 'grades.score':1})
db.restaurants.find({name:/mon/i},{_id:0, restaurant_id:1, name:1, borough:1, 'address.coord':1, cusine:1})
db.restaurants.find({name:/Mad/i},{_id:0, restaurant_id:1, name:1, borough:1, 'address.coord':1, cusine:1})